name: DS2 CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check files
        run: ls -R app

      - name: Build Docker image
        run: docker build -t ds2-project .

      - name: Run container test
        run: docker run -d -p 8080:80 ds2-project